# Generated by Django 2.0.7 on 2018-08-14 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(blank=True, max_length=75)),
                ('district_court_filter', models.CharField(blank=True, choices=[('', 'Criminal and civil cases'), ('1CV', 'Only criminal cases'), ('2CR', 'Only civil cases')], max_length=3)),
                ('only_new_cases', models.BooleanField(default=False)),
                ('live_updates', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('1CV', 'Civil'), ('2CR', 'Criminal'), ('3BK', 'Bankruptcy'), ('4AP', 'Appeals'), ('5MD', 'Multi-District Litigation'), ('6VC', 'Vaccine'), ('7CG', 'Congressional Record')], max_length=3)),
                ('website', models.URLField(help_text="The case's docket report site.", max_length=2000)),
                ('captured_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_date_filed', models.BooleanField(default=False, help_text='Is captured_time the date (but not the time) case was filed? Note: time is used for filtering.')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('type', models.CharField(choices=[('S', 'Supreme Court'), ('A', 'Appeals Court'), ('M', 'Judicial Panel on Multidistrict Litigation'), ('F', 'Federal Claims Court'), ('I', 'International Trade Court'), ('D', 'District Court'), ('B', 'Bankruptcy Court')], default='D', max_length=1)),
                ('has_feed', models.BooleanField(default=False)),
                ('publishes_all', models.BooleanField(default=False)),
                ('filing_types', models.CharField(blank=True, max_length=2000)),
                ('feed_url', models.URLField(blank=True, max_length=2000)),
                ('website', models.URLField(max_length=2000)),
                ('last_updated', models.DateTimeField(blank=True, editable=False, help_text="Date and time from the court's clock.", null=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourtGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('courts', models.ManyToManyField(to='pacertracker.Court')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_filed', models.DateTimeField(editable=False, help_text="According to court's clock.")),
                ('captured_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('number', models.IntegerField(blank=True, help_text='Document number, if available.', null=True)),
                ('website', models.URLField(blank=True, max_length=2000, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacertracker.Case')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacertracker.Court'),
        ),
        migrations.AddField(
            model_name='alert',
            name='courts',
            field=models.ManyToManyField(to='pacertracker.Court'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
